FirstNameLower=('taytum')
LastNameLower=('thioulon')
FirstNameUpper=('TAYTUM')
LastNameUpper=('THIOULON')
FirstNameTitle=('Taytum')
LastNameTitle=('Thioulon')
print('My name in titlecase',FirstNameTitle + LastNameTitle)
print('My name in uppercase',FirstNameUpper + LastNameUpper)
print('My name in uppercase',FirstNameLower + LastNameLower)